// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "akCqFtC5XoAiW7Vj6YUQy8PySSKR5s8uSX7pMmqUcvpHydhdgzTxddKOSIvImJQsVV2bms";
}
}
}

